# Generated by Django 5.1.3 on 2024-11-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_remove_librarianprofile_work_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='favorite_genres',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='favorite_genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
