# Generated by Django 5.1.3 on 2024-11-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_remove_memberprofile_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='membership_expiry',
            field=models.DateField(null=True),
        ),
    ]
