# Generated by Django 5.1.3 on 2024-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_alter_memberprofile_membership_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='notifications_preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_preferences',
            field=models.BooleanField(default=False),
        ),
    ]
