# Generated by Django 5.1.3 on 2024-11-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_remove_memberprofile_notifications_preferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_period', models.IntegerField(help_text='Duration of the subscription in days')),
                ('book_reservation_count', models.IntegerField(default=0, help_text='Number of books a user can reserve')),
                ('issue_book_count', models.IntegerField(default=0, help_text='Number of books a user can issue at a time')),
                ('external_library_access', models.BooleanField(default=False, help_text='Whether the subscription includes external library access')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
