# Generated by Django 5.1.3 on 2024-11-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='usermanagement.subscription'),
        ),
    ]
