# Generated by Django 5.1.3 on 2024-11-25 17:43

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_available_copies_book_reserved_copies_and_more'),
        ('usermanagement', '0009_subscription_status_user_gender_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('returnExtensionDate', models.IntegerField(null=True)),
                ('penalties', models.FloatField(default=0.0)),
                ('due_date', models.DateField(default=datetime.datetime(2024, 12, 9, 17, 43, 23, 940303, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('LOST', 'Issued'), ('DAMAGED', 'Damaged')], default='ISSUED', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
