# Generated by Django 5.1.3 on 2024-11-25 18:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_available_copies_book_reserved_copies_and_more'),
        ('usermanagement', '0010_bookissuetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuetransaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 18, 10, 28, 521712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'user')},
            },
        ),
    ]
