# Generated by Django 5.1.3 on 2024-11-27 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0011_alter_bookissuetransaction_due_date_bookreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuetransaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 8, 22, 28, 223904, tzinfo=datetime.timezone.utc)),
        ),
    ]
