# Generated by Django 5.1.3 on 2024-11-27 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0013_alter_bookissuetransaction_due_date_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuetransaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 16, 20, 35, 377016, tzinfo=datetime.timezone.utc)),
        ),
    ]
