# Generated by Django 5.1.3 on 2024-11-27 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0014_alter_bookissuetransaction_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='libriarian_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookissuetransaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 18, 16, 38, 269484, tzinfo=datetime.timezone.utc)),
        ),
    ]
