# Generated by Django 5.1.3 on 2024-11-28 18:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0017_alter_bookissuetransaction_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissuetransaction',
            name='issuedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.librarianprofile'),
        ),
        migrations.AlterField(
            model_name='bookissuetransaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 12, 18, 58, 53, 620078, tzinfo=datetime.timezone.utc)),
        ),
    ]
