# Generated by Django 5.1.3 on 2024-11-30 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0019_alter_bookissuetransaction_due_date_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissuetransaction',
            name='bookreturn',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookissuetransaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 14, 11, 10, 32, 231851, tzinfo=datetime.timezone.utc)),
        ),
    ]
