# Generated by Django 5.1.3 on 2024-11-30 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0020_bookissuetransaction_bookreturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissuetransaction',
            name='reportlostbook',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookissuetransaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 14, 14, 53, 3, 208762, tzinfo=datetime.timezone.utc)),
        ),
    ]
