# Generated by Django 5.1.3 on 2024-11-30 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0021_bookissuetransaction_reportlostbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuetransaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 14, 18, 51, 4, 924162, tzinfo=datetime.timezone.utc)),
        ),
    ]
