# Generated by Django 5.1.3 on 2024-11-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_tag_remove_genre_image_alter_genre_name_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
