# Generated by Django 5.1.3 on 2024-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_author_status_book_status_genre_status_tag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='reserved_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(default=1),
        ),
    ]
