# Generated by Django 5.1.3 on 2024-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_available_copies_book_reserved_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('removed', 'Removed')], default='available', max_length=20),
        ),
    ]
