# Generated by Django 5.1.3 on 2024-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_subscriptionlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='status',
        ),
        migrations.AddField(
            model_name='subscriptionlog',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
